--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/alvin0319/CustomItemLoader
build-by-default: true
branches:
  - master
  - pm4
projects:
  CustomItemLoader:
    path: ""
    libs:
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ^2.2.0
        branch: API-4.0.0
...
