name: CustomItemLoader
author: alvin0319
main: alvin0319\CustomItemLoader\CustomItemLoader
version: 2.3.1
api: 4.0.0

depend:
  - refAddonsManager

extensions:
  Core: ">=8.0"

permissions:
  customitemloader.command.rsc:
    default: op
  customitemloader.command:
    default: op
