name: CustomItemLoader
author: alvin0319
main: alvin0319\CustomItemLoader\CustomItemLoader
version: 2.1.0
api: 3.0.0

mcpe-protocol: 448

permissions:
  customitemloader.command.rsc:
    default: op
  customitemloader.command:
    default: op