name: CustomItemLoader
author: alvin0319
main: alvin0319\CustomItemLoader\CustomItemLoader
version: 2.2.0
api: 3.0.0

extensions:
  Core: ">=8.0"

mcpe-protocol: 465

permissions:
  customitemloader.command.rsc:
    default: op
  customitemloader.command:
    default: op
