name: CustomItemLoader
author: alvin0319
main: alvin0319\CustomItemLoader\CustomItemLoader
version: 3.2.0
api: 5.0.0

extensions:
  Core: ">=8.0"

permissions:
  customitemloader.command.rsc:
    default: op
  customitemloader.command:
    default: op
